"""empty message

Revision ID: 295ab837580b
Revises: 352d5b50c787
Create Date: 2022-11-27 22:01:24.095057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295ab837580b'
down_revision = '352d5b50c787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('todos', schema=None) as batch_op:
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')

    op.alter_column('todos', 'completed', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
