"""
This lesson title was misleading because the insert statement were done in the psql
not in this code

INSERT INTO persons (name) VALUES ('Amy');
INSERT INTO persons (name) VALUES ('Samu');
INSERT INTO persons (name) VALUES ('Wolfgang');
"""

from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

# need to define the URI to connect to our database
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres:postgres@localhost:5432/example'

#
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# This will link an instance of database that we can
# interact with SQLAlchemy to our Flask app
db = SQLAlchemy(app)

# SQLAlchemy's way of initializing instance of a table


class Person(db.Model):
    __tablename__ = 'persons'   # by default lowercase name of class
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(), nullable=False)

    def __repr__(self):
        return f'<Person ID: {self.id}. name: {self.name}>'


# actually creates that tables based on the db.Model that was configured
# if the table already exists, this will not do anything
with app.app_context():
    db.create_all()  


# querying contents of the database & grab first record
@app.route('/')
def index():
    person = Person.query.first()
    return f'Hello {person.name}!'


# querying contents of the database & grab some record
@app.route('/all')
def index_all():
    person = Person.query.all() # returns a list
    return f'Hello {person[2].name}!'  # show the name in index


# filter_by
@app.route('/jeff')
def jeff():
    query = Person.query.filter_by(name='Jeff') # find one with name Jeff 
    person = query.first()
    return f'Hello {person.name}!'

# filter and chaining the result
@app.route('/jeff2')
def jeff2():
    jeff = Person.query.filter(Person.name == 'Jeff').first()  # find one with name Jeff
    return f'Hello {jeff.name}!'

# like: find a record having a letter ('g') and show one
@app.route('/like')
def like():
    # using like
    result = Person.query.filter(Person.name.like('%g%')).all()
    count_g = Person.query.filter(Person.name.like('%g%')).count()
    return f'Hello {result[0].name}, names with g: {count_g}'

# to make case insensitive search use 'ilike' instead of 'like'

# get: find a record where id matches
@app.route('/get')
def get():
    # using get
    result = Person.query.get(4)
    return f'Hello {result.name}'


# show the query statement being generated by SQLAlchemy
@app.route('/query')
def some_query():
    # select * from persons where name = 'Jeff'
    query = Person.query.filter(Person.name == 'Jeff')
    return f'{query}'



if __name__ == '__main__':
    # set the debug mode to on
    app.debug = True
    app.run(host="0.0.0.0", port=5000)
